import { test, expect } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';

import { buildRenamePreview } from '../apps/webuiapps/src/lib/openVscodeSemantic';

const CONFIG_KEY = 'webuiapps-llm-config';
const TOOL_POLICY_KEY = 'openroom-tool-safety-policy-v1';

function makeOpenAIToolResponse(toolCalls: Array<{
  id: string;
  name: string;
  args: Record<string, unknown>;
}>) {
  return {
    choices: [
      {
        message: {
          content: '',
          tool_calls: toolCalls.map((toolCall) => ({
            id: toolCall.id,
            type: 'function',
            function: {
              name: toolCall.name,
              arguments: JSON.stringify(toolCall.args),
            },
          })),
        },
      },
    ],
  };
}

function makeOpenAITextResponse(content: string) {
  return {
    choices: [
      {
        message: {
          content,
          tool_calls: [],
        },
      },
    ],
  };
}

test.describe('Agent tool integration', () => {
  test.beforeEach(async ({ page, request }) => {
    await request.delete('/api/openroom-reset');
    await page.addInitScript(([configKey, toolPolicyKey]) => {
      localStorage.clear();
      localStorage.setItem(
        configKey,
        JSON.stringify({
          provider: 'openai',
          apiKey: 'sk-test',
          baseUrl: 'https://mock-llm.test/v1',
          model: 'gpt-4',
        }),
      );
      localStorage.setItem(
        toolPolicyKey,
        JSON.stringify({
          autoVerifyFixes: true,
          allowWorkspaceCommands: true,
          allowSemanticRefactors: true,
          allowBackgroundWatches: false,
          requirePreviewBeforeMutation: false,
        }),
      );
    }, [CONFIG_KEY, TOOL_POLICY_KEY]);
  });

  test('shows tool inspector sections in settings', async ({ page }) => {
    await page.goto('/');
    await page.locator('[data-testid="settings-btn"]').click();

    const modal = page.locator('[data-testid="settings-modal"]');
    await expect(modal).toBeVisible();
    await expect(modal).toContainText('Tool Inspector');
    await expect(page.locator('[data-testid="tool-inspector"]')).toBeVisible();
    await expect(modal).toContainText('Safety Policy');
    await expect(modal).toContainText('Recent Tool Activity');
  });

  test('auto-verifies diagnostics after a file mutation before final response', async ({ page }) => {
    let llmCallCount = 0;
    await page.route('**/api/llm-proxy', async (route) => {
      llmCallCount += 1;

      if (llmCallCount === 1) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(
            makeOpenAIToolResponse([
              {
                id: 'tc_diag_1',
                name: 'structured_diagnostics',
                args: { command: 'pnpm exec tsc --noEmit' },
              },
            ]),
          ),
        });
        return;
      }

      if (llmCallCount === 2) {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(
            makeOpenAIToolResponse([
              {
                id: 'tc_preview',
                name: 'preview_changes',
                args: {
                  operation: 'write',
                  file_path: 'apps/notes/data/notes/auto-fix-e2e.json',
                  content: JSON.stringify({
                    id: 'auto-fix-e2e',
                    title: 'Auto fix E2E',
                    content: 'Generated by Playwright',
                    tags: ['e2e'],
                    pinned: false,
                    createdAt: 1776200000000,
                    updatedAt: 1776200000000,
                  }),
                },
              },
              {
                id: 'tc_write',
                name: 'file_write',
                args: {
                  file_path: 'apps/notes/data/notes/auto-fix-e2e.json',
                  content: JSON.stringify({
                    id: 'auto-fix-e2e',
                    title: 'Auto fix E2E',
                    content: 'Generated by Playwright',
                    tags: ['e2e'],
                    pinned: false,
                    createdAt: 1776200000000,
                    updatedAt: 1776200000000,
                  }),
                },
              },
              {
                id: 'tc_reply_early',
                name: 'respond_to_user',
                args: {
                  character_expression: {
                    content: 'I fixed it.',
                  },
                  user_interaction: {
                    suggested_replies: ['Thanks', 'Show me', 'Try again'],
                  },
                },
              },
            ]),
          ),
        });
        return;
      }

      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(
          makeOpenAIToolResponse([
            {
              id: 'tc_reply_final',
              name: 'respond_to_user',
              args: {
                character_expression: {
                  content: 'Diagnostics are clean now.',
                },
                user_interaction: {
                  suggested_replies: ['Nice', 'Show inspector', 'Open IDE'],
                },
              },
            },
          ]),
        ),
      });
    });

    await page.route('**/api/openvscode/run', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify(
          llmCallCount === 1
            ? {
                command: 'pnpm exec tsc --noEmit',
                cwd: '.',
                exitCode: 2,
                timedOut: false,
                durationMs: 12,
                stdout: '',
                stderr:
                  'src/example.ts(3,5): error TS2322: Type "number" is not assignable to type "string".',
              }
            : {
                command: 'pnpm exec tsc --noEmit',
                cwd: '.',
                exitCode: 0,
                timedOut: false,
                durationMs: 10,
                stdout: '',
                stderr: '',
              },
        ),
      });
    });

    await page.goto('/');
    await page.locator('[data-testid="chat-input"]').fill('Fix the TypeScript issue and verify it.');
    await page.locator('[data-testid="send-btn"]').click();

    await expect(page.locator('[data-testid="chat-messages"]')).toContainText(
      'Diagnostics are clean now.',
    );
    await expect(page.locator('[data-testid="chat-messages"]')).not.toContainText('I fixed it.');
    expect(llmCallCount).toBe(3);
  });

  test('applies a semantic rename through the chat loop', async ({ page }) => {
    const tempDirName = `tmp-semantic-rename-${Date.now()}`;
    const tempDirPath = path.join(process.cwd(), tempDirName);
    fs.mkdirSync(tempDirPath, { recursive: true });
    const filePath = path.join(tempDirPath, 'renameTarget.ts');
    fs.writeFileSync(
      filePath,
      ['export function OldName() {', '  return OldName.name;', '}', '', 'console.log(OldName());'].join('\n'),
      'utf-8',
    );

    try {
      const preview = buildRenamePreview({
        rootDir: process.cwd(),
        directory: tempDirName,
        symbol: 'OldName',
        newName: 'NewName',
      });

      let llmCallCount = 0;
      await page.route('**/api/llm-proxy', async (route) => {
        llmCallCount += 1;
        if (llmCallCount === 1) {
          await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(
              makeOpenAIToolResponse([
                {
                  id: 'rename_preview',
                  name: 'rename_preview',
                  args: {
                    symbol: 'OldName',
                    new_name: 'NewName',
                    directory: tempDirName,
                  },
                },
              ]),
            ),
          });
          return;
        }

        if (llmCallCount === 2) {
          await route.fulfill({
            status: 200,
            contentType: 'application/json',
            body: JSON.stringify(
              makeOpenAIToolResponse([
                {
                  id: 'apply_rename',
                  name: 'apply_semantic_rename',
                  args: {
                    symbol: 'OldName',
                    new_name: 'NewName',
                    preview_signature: preview.signature,
                    directory: tempDirName,
                  },
                },
              ]),
            ),
          });
          return;
        }

        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(
            makeOpenAIToolResponse([
              {
                id: 'rename_done',
                name: 'respond_to_user',
                args: {
                  character_expression: {
                    content: 'Semantic rename applied.',
                  },
                  user_interaction: {
                    suggested_replies: ['Show diff', 'Open file', 'Undo'],
                  },
                },
              },
            ]),
          ),
        });
      });

      await page.goto('/');
      await page.locator('[data-testid="chat-input"]').fill('Rename OldName to NewName in the IDE workspace.');
      await page.locator('[data-testid="send-btn"]').click();

      await expect(page.locator('[data-testid="chat-messages"]')).toContainText(
        'Semantic rename applied.',
      );
      expect(fs.readFileSync(filePath, 'utf-8')).toContain('NewName');
      expect(fs.readFileSync(filePath, 'utf-8')).not.toContain('OldName');
    } finally {
      fs.rmSync(tempDirPath, { recursive: true, force: true });
    }
  });
});
